package fulecation

class HasSticker {
    
    Long id
    Long version
    
    User onwer
    Boolean hasExtra
    Boolean hasShiny
    Integer stickerNumber
    
    static constraints = {
        onwer (unique: ['stickerNumber'])
    }
    
    static AddOrUpdate(User user, Boolean hasExtra, Boolean hasShiny, Integer stickerNumber)
    {
        def hasSticker = HasSticker.findWhere(onwer: user, stickerNumber: stickerNumber)
         
        if(!hasSticker)
        {
            hasSticker = new HasSticker(onwer: user, hasExtra: hasExtra, hasShiny: hasShiny, stickerNumber: stickerNumber)
        }
        
        hasSticker.save flush:true
    }
    
    static album_sections = [
            "Outras",
            "Brasil",
            "Croácia",
            "México",
            "Camarões",
            "Espanha",
            "Holanda",
            "Chile",
            "Austrália",
            "Colombia",
            "Grécia",
            "Costa do Marfim",
            "Japan",
            "Uruguai",
            "Costa Rica",
            "Inglaterra",
            "Itália",
            "Suíça",
            "Equador",
            "França",
            "Honduras",
            "Argentina",
            "Bósnia e Herzegovina",
            "Iran",
            "Nigéria",
            "Alemanha",
            "Portugal",
            "Gana",
            "EUA",
            "Bélgica",
            "Argélia",
            "Rússia",
            "Coréia do Sul",
        
    ]
        
        
    static GetCode(Integer nr)
    {
        if(nr <= 639)
        {
            return nr.toString();
        }
        else
        {
            def codes = ["J1", "J2", "J3", "J4", "L1", "L2", "L3", "L4", "W1"]
            
            return (codes[nr - 640]);
        }
    }
   
    static GetName(Integer nr)
    {
        if(nr < names.size)
        return names[nr]
        else
        return "Unknown"
    }
    
    static names = 
    [
        "Panini special sticker", 
        "FIFA - My game is fair play", 
        "Official Emblem (puzzle 1)", 
        "Official Emblem (puzzle 2)", 
        "Official Mascot (puzzle 2)", 
        "Official Mascot (puzzle 1)", 
        "FIFA World Cup Trophy", 
        "Brazuca - Official Ball", 
        "Estádio Mineirão - Belo Horizonte (puzzle 1)", 
        "Estádio Mineirão - Belo Horizonte (puzzle 2)", 
        "Estádio Nacional - Brasília (puzzle 1)", 
        "Estádio Nacional - Brasília (puzzle 2)", 
        "Arena Pantanal - Cuiabá (puzzle 1)", 
        "Arena Pantanal - Cuiabá (puzzle 2)", 
        "Arena da Baixada - Curitiba (puzzle 1)", 
        "Arena da Baixada - Curitiba (puzzle 2)", 
        "Estádio Castelão - Fortaleza (puzzle 1)", 
        "Estádio Castelão - Fortaleza (puzzle 2)", 
        "Arena Amazônia - Manaus (puzzle 1)", 
        "Arena Amazônia - Manaus (puzzle 2)", 
        "Estádio das Dunas - Natal (puzzle 1)", 
        "Estádio das Dunas - Natal (puzzle 2)", 
        "Estádio Beira-Rio - Porto Alegre (puzzle 1)", 
        "Estádio Beira-Rio - Porto Alegre (puzzle 2)", 
        "Arena Pernambuco - Recife (puzzle 1)", 
        "Arena Pernambuco - Recife (puzzle 2)", 
        "Estádio Maracanã - Rio de Janeiro (puzzle 1)", 
        "Estádio Maracanã - Rio de Janeiro (puzzle 2)", 
        "Arena Fonte Nova - Salvador (puzzle 1)", 
        "Arena Fonte Nova - Salvador (puzzle 2)", 
        "Arena Corinthians - São Paolo (puzzle 1)", 
        "Arena Corinthians - São Paolo (puzzle 2)", 
        "Badge", 
        "Team", 
        "Júlio César", 
        "Thiago Silva", 
        "David Luiz", 
        "Dani Alves", 
        "Marcelo", 
        "Dante", 
        "Ramires", 
        "Paulinho", 
        "Luiz Gustavo", 
        "Hernanes", 
        "Oscar", 
        "Bernard", 
        "Willian", 
        "Robinho", 
        "Neymar Jr.", 
        "Hulk", 
        "Fred", 
        "Badge", 
        "Team", 
        "Stipe Pletikosa", 
        "Darijo Srna", 
        "Vedran Ćorluka", 
        "Ivan Strinić", 
        "Dejan Lovren", 
        "Domagoj Vida", 
        "Šime Vrsaljko", 
        "Ognjen Vukojević", 
        "Niko Kranjčar", 
        "Luka Modrić", 
        "Ivan Rakitić", 
        "Mateo Kovačić", 
        "Ivan Perišić", 
        "Ivica Olić", 
        "Eduardo", 
        "Nikica Jelavić", 
        "Mario Mandžukić", 
        "Badge", 
        "Team", 
        "Jesús Corona", 
        "Rafael Márquez", 
        "Francisco Rodríguez", 
        "Héctor Moreno", 
        "Miguel Layún", 
        "Paul Aguilar", 
        "Diego Reyes", 
        "Andrés Guardado", 
        "Héctor Herrera", 
        "Carlos Peña", 
        "Luis Montes", 
        "Giovani Dos Santos", 
        "Aldo De Nigris", 
        "Javier Hernández", 
        "Oribe Peralta", 
        "Raúl Jiménez", 
        "Moisés Muñoz", 
        "Badge", 
        "Team", 
        "Charles Itandje", 
        "Aurélien Chedjou", 
        "Nicolas Nikoulou", 
        "Dany Nounkeu", 
        "Henri Bedimo", 
        "Benoît Assou-Ekotto", 
        "Joel Matip", 
        "Stéphane Mbia", 
        "Alex Song", 
        "Eyong Enoh", 
        "Jean Makoun", 
        "Landry Nguémo", 
        "Vincent Aboubakar", 
        "Eric Choupo-Moting", 
        "Benjamin Moukandjo", 
        "Pierre Webó", 
        "Samuel Eto'o", 
        "Badge", 
        "Team", 
        "Iker Casillas", 
        "Sergio Ramos", 
        "Gerard Piqué", 
        "Raúl Albiol", 
        "Álvaro Arbeloa", 
        "Jordi Alba", 
        "Xabi Alonso", 
        "Sergio Busquets", 
        "Havi Hernández", 
        "Andrés Iniesta", 
        "Cesc Fábregas", 
        "David Silva", 
        "Jesús Navas", 
        "Juan Mata", 
        "Pedro Rodríguez", 
        "David Villa", 
        "Álvaro Negredo", 
        "Badge", 
        "Team", 
        "Jasper Cillessen", 
        "Daryl Janmaat", 
        "Stefan De Vrij", 
        "Ron Vlaar", 
        "Bruno Martins Indi", 
        "Daley Blind", 
        "Jordy Clasie", 
        "Nigel De Jong", 
        "Kevin Strootman", 
        "Rafael Van Der Vaart", 
        "Wesley Sneijder", 
        "Arjen Robben", 
        "Memphis Depay", 
        "Dirk Kuyt", 
        "Jeremain Lens", 
        "Klaas-Jan Huntelaar", 
        "Robin Van Persie", 
        "Badge", 
        "Team", 
        "Claudio Bravo", 
        "Marcos González", 
        "Eugenio Mena", 
        "Gonzalo Jara", 
        "José Rojas", 
        "Gary Medel", 
        "Mauricio Isla", 
        "Jorge Valdivia", 
        "David Pizarro", 
        "Matías Fernández", 
        "Marcelo Díaz", 
        "Arturo Vidal", 
        "Jean Beausejour", 
        "Charles Aránguiz", 
        "Mauricio Pinilla", 
        "Eduardo Vargas", 
        "Alexis Sánchez", 
        "Badge", 
        "Team", 
        "Mathew Ryan", 
        "Lucas Neill", 
        "Jason Davidson", 
        "Mark Milligan", 
        "Ivan Franjic", 
        "Rhys Williams", 
        "Brett Holman", 
        "Mile Jedinak", 
        "Matt McKay", 
        "Mark Bresciano", 
        "Tom Rogic", 
        "Tim Cahill", 
        "Dario Vidosic", 
        "Tommy Oar", 
        "Ben Halloran", 
        "Mathew Leckie", 
        "Joshua Kennedy", 
        "Badge", 
        "Team", 
        "David Ospina", 
        "Mario Yepes", 
        "Cristian Zapata", 
        "Luis Perea", 
        "Pablo Armero", 
        "Camilo Zuniga", 
        "Aldo Ramirez", 
        "Carlos Sanchez", 
        "Abel Aguilar", 
        "Fredy Guarin", 
        "Juan Cuadrado", 
        "Macnelly Torres", 
        "Carlos Bacca", 
        "James Rodriguez", 
        "Teofilo Gutierrez", 
        "Jackson Martinez", 
        "Falcao Colombia", 
        "Badge", 
        "Team", 
        "Orestis Karnezis", 
        "Vasilis Torosidis", 
        "Sokratis Papastathopoulos", 
        "Giannis Maniatis", 
        "Dimitris Siovas", 
        "Jose Holebas", 
        "Kostas Manolas", 
        "Andreas Samaris", 
        "Giorgos Karagounis", 
        "Kostas Katsouranis", 
        "Alexandros Tziolis", 
        "Panagiotis Kone", 
        "Sotiris Ninis", 
        "Giorgos Samaras", 
        "Dimitris Salpingidis", 
        "Fanis Gekas", 
        "Kostas Mitroglou", 
        "Badge", 
        "Team", 
        "Boubacar Barry", 
        "Kolo Toure", 
        "Serge Aurier", 
        "Souleymane Bamba", 
        "Arthur Boka", 
        "Benjamin Angoua", 
        "Didier Zokora", 
        "Yaya Toure", 
        "Cheick Tiote", 
        "Jean-Jacques Gosso", 
        "Serey Die", 
        "Romaric", 
        "Gervinho", 
        "Salomon Kalou", 
        "Wilfried Bony", 
        "Lacina Traore", 
        "Didier Drogba", 
        "Badge", 
        "Team", 
        "Eiji Kawashima", 
        "Maya Yoshida", 
        "Yasuyuki Konno", 
        "Atsuto Uchida", 
        "Yuto Nagatomo", 
        "Gotoku Sakai", 
        "Hiroki Sakai", 
        "Masato Morishige", 
        "Yasuhito Endo", 
        "Makoto Hasebe", 
        "Keisuke Honda", 
        "Hotaru Yamaguchi", 
        "Hiroshi Kiyotake", 
        "Shinji Kagawa", 
        "Shinji Okazaki", 
        "Yoichiro Kakitani", 
        "Yuya Osako", 
        "Badge", 
        "Team", 
        "Fernando Muslera", 
        "Diego Lugano", 
        "Diego Godin", 
        "Maxi Pereira", 
        "Martin Caceres", 
        "Alvaro Pereira", 
        "Walter Gargano", 
        "Egidio Arevalo Rios", 
        "Diego Perez", 
        "Alvaro Gonzalez", 
        "Cristian Rodriguez", 
        "Gaston Ramirez", 
        "Christian Stuani", 
        "Abel Hernandez", 
        "Diego Forlan", 
        "Edinson Cavani", 
        "Luis Suarez", 
        "Badge", 
        "Team", 
        "Keylor Navas", 
        "Giancarlo Gonzalez", 
        "Michael Umana", 
        "Cristian Gamboa", 
        "Johnny Acosta", 
        "Junior Diaz", 
        "Roy Miller", 
        "Ariel Rodriguez", 
        "Christian Bolanos", 
        "Jose Miguel Cubero", 
        "Celso Borges", 
        "Michael Barrantes", 
        "Yeltsin Tejeda", 
        "Diego Calvo", 
        "Bryan Ruiz", 
        "Joel Campbell", 
        "Alvaro Saborio", 
        "Badge", 
        "Team", 
        "Joe Hart", 
        "Ashley Cole", 
        "Glen Johnson", 
        "Gary Cahill", 
        "Phil Jagielka", 
        "Kyle Walker", 
        "Leighton Baines", 
        "Steven Gerrard", 
        "Frank Lampard", 
        "Michael Carrick", 
        "Jack Wilshere", 
        "James Milner", 
        "Andros Townsend", 
        "Alex Oxlade-Chamberlain", 
        "Danny Welbeck", 
        "Daniel Sturridge", 
        "Wayne Rooney", 
        "Badge", 
        "Team", 
        "Gianluigi Buffon", 
        "Andrea Barzagli", 
        "Leonardo Bonucci", 
        "Giorgio Chiellini", 
        "Ignazio Abate", 
        "Mattia De Sciglio", 
        "Tiago Motta", 
        "Daniele De Rossi", 
        "Andrea Pirlo", 
        "Riccardo Montolivo", 
        "Claudio Marchisio", 
        "Emanuele Giaccherini", 
        "Antonio Candreva", 
        "Alessio Cerci", 
        "Alberto Gilardino", 
        "Giuseppe Rossi", 
        "Mario Balotelli", 
        "Badge", 
        "Team", 
        "Diego Benaglio", 
        "Stephan Lichsteiner", 
        "Ricrado Rodriguez", 
        "Steve Von Bergan", 
        "Fabian Schär", 
        "Philippe Senderos", 
        "Johan Djourou", 
        "Tranquillo Barnetta", 
        "Gökhan Inler", 
        "Valon Behrami", 
        "Blerim Džemaili", 
        "Granit Xhaka", 
        "Valentin Stocker", 
        "Xherdan Shaqiri", 
        "Admir Mehmedi", 
        "Eren Derdiyok", 
        "Haris Seferović", 
        "Badge", 
        "Team", 
        "Alexander Domínguez", 
        "Walter Ayoví", 
        "Frickson Erazo", 
        "Jorge Guagua", 
        "Gabriel Achilier", 
        "Juan Carlos Paredes", 
        "Édison Méndez", 
        "Enner Valencia", 
        "Luis Saritama", 
        "Christian Noboa", 
        "Segundo Castillo", 
        "Joao Rojas", 
        "Antonio Valencia", 
        "Renato Ibarra", 
        "Jefferson Montero", 
        "Felipe Caicedo", 
        "Jaime Ayoví", 
        "Badge", 
        "Team", 
        "Hugo Lloris", 
        "Patrice Evra", 
        "Mathieu Debuchy", 
        "Raphaël Varane", 
        "Laurent Koscielny", 
        "Mamadou Sakho", 
        "Éric Abidal", 
        "Moussa Sissoko", 
        "Yohan Cabaye", 
        "Blaise Matuidi", 
        "Paul Pogba", 
        "Mathieu Valbuena", 
        "Samir Nasri", 
        "Franck Ribéry", 
        "Loïc Rémy", 
        "Olivier Giroud", 
        "Karim Benzema", 
        "Badge", 
        "Team", 
        "Noel Valladares", 
        "Emilio Izaguirre", 
        "Víctor Bernárdez", 
        "Maynor Figueroa", 
        "Juan Carlos Garcia", 
        "Brayan Beckeles", 
        "Jorge Carlos", 
        "Arnold Peralta", 
        "Boniek Garcia", 
        "Roger Espinoza", 
        "Luis Garrido", 
        "Wilson Palacios", 
        "Andy Najar", 
        "Jerry Palacios", 
        "Marvin Chávez", 
        "Jerry Bengtson", 
        "Carlo Costly", 
        "Badge", 
        "Team", 
        "Sergio Romero", 
        "Pablo Zabaleta", 
        "Ezequiel Garay", 
        "Federico Fernández", 
        "Hugo Campagnaro", 
        "Marcos Rojo", 
        "Lucas Biglia", 
        "Javier Mascherano", 
        "Fernando Gago", 
        "Éver Banega", 
        "Maxi Rodríguez", 
        "Ángel di María", 
        "Ezequiel Lavezzi", 
        "Rodrigo Palacio", 
        "Sergio Agüero", 
        "Gonzalo Higuaín", 
        "Lionel Messi", 
        "Badge", 
        "Team", 
        "Asmir Begović", 
        "Emir Spahić", 
        "Avdija Vršajević", 
        "Ermin Bičakčić", 
        "Toni Šunjić", 
        "Sead Kolašinac", 
        "Senad Lulić", 
        "Senijad Ibričić", 
        "Mensur Mujdža", 
        "Haris Medunjanin", 
        "Zvjezdan Misimović", 
        "Miralem Pjanić", 
        "Sejad Salihović", 
        "Adnan Zahirović", 
        "Izet Hajrović", 
        "Vedad Ibišević", 
        "Edin Džeko", 
        "Badge", 
        "Team", 
        "Daniel Davari", 
        "Jalal Hosseini", 
        "Khosro Heydari", 
        "Hossein Mahini", 
        "Pejman Montazeri", 
        "Ehsan Hajsafi", 
        "Hashem Beikzadeh", 
        "Amir Hossein Sadeghi", 
        "Javad Nekounam", 
        "Andranik Teymourian", 
        "Mojtaba Jabbari", 
        "Masoud Shojaei", 
        "Ashkan Dejagah", 
        "Reza Ghoochannejhad", 
        "Gholamreza Rezaei", 
        "Karim Ansarifard", 
        "Mohammad Khalatbari", 
        "Badge", 
        "Team", 
        "Vincent Enyeama", 
        "Joseph Yobo", 
        "Efe Ambrose", 
        "Godfrey Oboabona", 
        "Elderson Echiejile", 
        "Azubuike Egwuekwe", 
        "Kenneth Omeruo", 
        "John Ogu", 
        "John Obi Mikel", 
        "Ogenyi Onazi", 
        "Sunday Mba", 
        "Victor Moses", 
        "Nnamdi Oduamadi", 
        "Ahmed Musa", 
        "Ideye Brown", 
        "Shola Ameobi", 
        "Emmanuel Emenike", 
        "Badge", 
        "Team", 
        "Manuel Neuer", 
        "Philipp Lahm", 
        "Per Mertesacker", 
        "Jérôme Boateng", 
        "Mats Hummels", 
        "Marcel Schmelzer", 
        "Sami Khedira", 
        "Bastian Schweinsteiger", 
        "Toni Kroos", 
        "Mesut Özil", 
        "Mario Götze", 
        "Julian Draxler", 
        "Marco Reus", 
        "André Schürrle", 
        "Lukas Podolski", 
        "Thomas Müller", 
        "Miroslav Klose", 
        "Badge", 
        "Team", 
        "Rui Patricio", 
        "Pepe", 
        "Bruno Alves", 
        "João Pereira", 
        "Fábio Coentrão", 
        "Ricardo Costa", 
        "Antunes", 
        "Josué", 
        "Miguel Veloso", 
        "João Moutinho", 
        "Raul Meireles", 
        "William Carvalho", 
        "Nani", 
        "Silvestre Varela", 
        "Cristiano Ronaldo", 
        "Hélder Postiga", 
        "Hugo Almeida", 
        "Badge", 
        "Team", 
        "Fatau Dauda", 
        "Samuel Inkoom", 
        "Jonathan Mensah", 
        "Daniel Opare", 
        "Harrison Afful", 
        "John Boye", 
        "Michael Essien", 
        "Emmanuel Badu", 
        "Kwadwo Asamoah", 
        "Sulley Muntari", 
        "Wakaso Mubarak", 
        "Kevin-Prince Boateng", 
        "Waris Majeed", 
        "Christian Atsu", 
        "André Ayew", 
        "Jordan Ayew", 
        "Asamoah Gyan", 
        "Badge", 
        "Team", 
        "Tim Howard", 
        "Geoff Cameron", 
        "Omar Gonzalez", 
        "Clarence Goodson", 
        "Matt Besler", 
        "Fabian Johnson", 
        "DaMarcus Beasley", 
        "Jermaine Jones", 
        "Michael Bradley", 
        "Brad Evans", 
        "Graham Zusi", 
        "Mix Diskerud", 
        "Clint Dempsey", 
        "Aron Johannsson", 
        "Landon Donovan", 
        "Eddie Johnson", 
        "Jozy Altidore", 
        "Badge", 
        "Team", 
        "Thibaut Courtois", 
        "Vincent Kompany", 
        "Toby Alderweireld", 
        "Jan Vertonghen", 
        "Daniel Van Buyten", 
        "Thomas Vermaelen", 
        "Steven Defour", 
        "Axel Witsel", 
        "Mousa Dembélé", 
        "Kevin De Bruyne", 
        "Marouane Fellaini", 
        "Nacer Chadli", 
        "Eden Hazard", 
        "Dries Mertens", 
        "Kevin Mirallas", 
        "Romelu Lukaku", 
        "Christian Benteke", 
        "Badge", 
        "Team", 
        "Raïs M'Bolhi", 
        "Madjid Bougherra", 
        "Carl Medjani", 
        "Adlène Guedioura", 
        "Djamel Mesbah", 
        "Mehdi Mostefa", 
        "Faouzi Ghoulam", 
        "Essaid Belkalem", 
        "Hassan Yebda", 
        "Mehdi Lacen", 
        "Yacine Brahimi", 
        "Saphir Taïder", 
        "Sofiane Feghouli", 
        "Rafik Djebbour", 
        "Nabil Ghilas", 
        "El Arbi Soudani", 
        "Islam Slimani", 
        "Badge", 
        "Team", 
        "Igor Akinfeev", 
        "Sergei Ignashevich", 
        "Aleksei Berezutski", 
        "Vasili Berezutski", 
        "Dmitri Kombarov", 
        "Aleksandr Anyukov", 
        "Aleksei Kozlov", 
        "Roman Shirokov", 
        "Igor Denisov", 
        "Viktor Fayzulin", 
        "Vladimir Bystrov", 
        "Denis Glushakov", 
        "Aleksandr Samedov", 
        "Alan Dzagoev", 
        "Fedor Smolov", 
        "Aleksandr Kokorin", 
        "Aleksandr Kerzhakov", 
        "Badge", 
        "Team", 
        "Jung Sung-Ryong", 
        "Kwak Tae-Hwi", 
        "Hong Jeong-Ho", 
        "Kim Young-Gwon", 
        "Park Joo-Ho", 
        "Shin Kwang-Hoon", 
        "Lee Yong", 
        "Han Kook-Young", 
        "Lee Chung-Yong", 
        "Ki Sung-Yueng", 
        "Koo Ja-Cheol", 
        "Kim Bo-Kyung", 
        "Son Heung-Min", 
        "Ji Dong-Won", 
        "Kim Shin-Wook", 
        "Park Chu-Young", 
        "Lee Keun-Ho"
    ]
}
